### ISSUE TITLE
Add Module Maps to .framework

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/cerbero#4]
In order for the generated OpenWebRTC.framework to work with CocoaPods, and that users should be able to add it as `@import OpenWebRTC;`, Module Maps should be added. Hopefully this removes the need to add a custom HEADER_SEARCH_PATHS after the framework has been installed.

Some more info is available here:

http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by stefanalund** [comment]
Information about failing CocoaPod installation:

```
[!] The 'Pods' target has transitive dependencies that include static binaries: (/private/var/folders/g7/9m135pmn5sb0391hrynxp1dm0000gq/T/CocoaPods/Lint/Pods/OpenWebRTC/OpenWebRTC.framework)

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:366:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:354:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:354:in `block in verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:351:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:351:in `verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:94:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/validator.rb:311:in `install_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/validator.rb:215:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/validator.rb:211:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/validator.rb:211:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/validator.rb:73:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.0/lib/pod/command/trunk/push.rb:109:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.0/lib/pod/command/trunk/push.rb:58:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```
