### ISSUE TITLE
cerbero.errors.FatalError: Fatal Error: Mac version 10.12.2 not supported

### ISSUE THREAD

**Issue by 983563622** [EricssonResearch/cerbero#59]
Traceback (most recent call last):
  File "./cerbero-uninstalled", line 8, in <module>
    from cerbero.main import main
  File "./cerbero/main.py", line 19, in <module>
    from cerbero import hacks
  File "./cerbero/hacks.py", line 132, in <module>
    from cerbero.utils.shell import call as shell_call
  File "./cerbero/utils/shell.py", line 42, in <module>
    PLATFORM = system_info()[0]
  File "./cerbero/utils/__init__.py", line 251, in system_info
    raise FatalError("Mac version %s not supported" % ver)
cerbero.errors.FatalError: Fatal Error: Mac version 10.12.2 not supported

**Comment by nirbheek** [comment]
This is already fixed in the [upstream Cerbero](https://cgit.freedesktop.org/gstreamer/cerbero/commit/?id=250462859dd3377ceac0f24bc9645ede605a39a1). Someone needs to rebase OWRTC Cerbero to match upstream.

**Comment by 983563622** [comment]
it's very good,thanks!
